<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Students Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4A90E2;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #4A90E2;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table thead {
            background-color: #4A90E2;
            color: white;
        }
        table th {
            padding: 10px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        table td {
            padding: 8px 10px;
            border: 1px solid #ddd;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        table tbody tr:hover {
            background-color: #f0f5ff;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        .total {
            font-weight: bold;
            background-color: #f0f5ff;
            text-align: right;
            padding: 10px;
        }
        .no-data {
            text-align: center;
            padding: 20px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Students Report</h1>
        <p>Complete Student Information</p>
    </div>

    <div class="report-info">
        <p><strong>Generated:</strong> {{ $exportDate }}</p>
        <p><strong>Total Records:</strong> {{ count($students) }}</p>
    </div>

    @if(count($students) > 0)
        <table>
            <thead>
                <tr>
                    <th width="5%">ID</th>
                    <th width="15%">First Name</th>
                    <th width="12%">Middle Name</th>
                    <th width="15%">Last Name</th>
                    <th width="20%">Email</th>
                    <th width="12%">Contact</th>
                    <th width="8%">Age</th>
                    <th width="13%">Degree</th>
                </tr>
            </thead>
            <tbody>
                @foreach($students as $student)
                    <tr>
                        <td>{{ $student->id }}</td>
                        <td>{{ $student->fname }}</td>
                        <td>{{ $student->mname ?? '-' }}</td>
                        <td>{{ $student->lname }}</td>
                        <td>{{ $student->email }}</td>
                        <td>{{ $student->contact_no ?? 'N/A' }}</td>
                        <td>{{ $student->age ?? '-' }}</td>
                        <td>{{ $student->degree?->title ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No student records found.</p>
        </div>
    @endif

    <div class="footer">
        <p>This document was automatically generated by the AVD Activity System.</p>
        <p>&copy; {{ date('Y') }} All rights reserved.</p>
    </div>
</body>
</html>
