<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4A90E2;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #4A90E2;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table thead {
            background-color: #4A90E2;
            color: white;
        }
        table th {
            padding: 10px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        table td {
            padding: 8px 10px;
            border: 1px solid #ddd;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        table tbody tr:hover {
            background-color: #f0f5ff;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        .no-data {
            text-align: center;
            padding: 20px;
            color: #999;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 11px;
            font-weight: bold;
        }
        .badge-admin {
            background-color: #E74C3C;
            color: white;
        }
        .badge-user {
            background-color: #3498DB;
            color: white;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Users Report</h1>
        <p>System Users Information</p>
    </div>

    <div class="report-info">
        <p><strong>Generated:</strong> {{ $exportDate }}</p>
        <p><strong>Total Records:</strong> {{ count($users) }}</p>
    </div>

    @if(count($users) > 0)
        <table>
            <thead>
                <tr>
                    <th width="8%">ID</th>
                    <th width="25%">Name</th>
                    <th width="40%">Email</th>
                    <th width="15%">Role</th>
                    <th width="12%">Created</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ ucfirst($user->role ?? 'user') }}</td>
                        <td>{{ $user->created_at?->format('Y-m-d') ?? '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No user records found.</p>
        </div>
    @endif

    <div class="footer">
        <p>This document was automatically generated by the AVD Activity System.</p>
        <p>&copy; {{ date('Y') }} All rights reserved.</p>
    </div>
</body>
</html>
